# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambdaMaxC <- function(subDataa, strata_size, norm_method, features_mean, features_sd) {
    .Call(`_bigSurvSGD_lambdaMaxC`, subDataa, strata_size, norm_method, features_mean, features_sd)
}

oneChunkC <- function(subData, Beta, beta_type, strata_size, batch_size, t, m, v, vHat, lr_const, lr_tau, opt_method, norm_method, b1, b2, eps, lambda, alpha, features_mean, features_sd) {
    .Call(`_bigSurvSGD_oneChunkC`, subData, Beta, beta_type, strata_size, batch_size, t, m, v, vHat, lr_const, lr_tau, opt_method, norm_method, b1, b2, eps, lambda, alpha, features_mean, features_sd)
}

oneObsPlugingC <- function(subDataa, Beta, strata_size, norm_method, features_mean, features_sd) {
    .Call(`_bigSurvSGD_oneObsPlugingC`, subDataa, Beta, strata_size, norm_method, features_mean, features_sd)
}

